# yaml-language-server: $schema=https://json-schema.axonivy.com/14.0-dev/config/variables.json
Variables:
  Amazon:
    Comprehend:
      # Secret key to access amazon comprehend
      #[password]
      SecretKey: ${decrypt:}
      # Access key to access amazon comprehend
      #[password]
      AccessKey: ${decrypt:}
      # Session token to access amazon comprehend
      #[password]
      SessionToken: ${decrypt:}
      # A region e.g. 'us-east-2'.
      Region: ""
