Variables:

  Amazon.Comprehend:

    # Secret key to access amazon comprehend
    # [password] 
    SecretKey: ""
    
    # Access key to access amazon comprehend
    # [password]
    AccessKey: ""
