# yaml-language-server: $schema=https://json-schema.axonivy.com/app/11.4.1/variables.json
Variables:
  Amazon:
    Comprehend:
      # Secret key to access amazon comprehend
      # [password]
      SecretKey: ""
      # Access key to access amazon comprehend
      # [password]
      AccessKey: ""
      # Session token to access amazon comprehend
      # [password]
      SessionToken: ""
